export const jokes = [
  "My code has two modes: \"it works\" and \"I have no idea what's happening.\"",
  "VS Code: 47 extensions. Productivity: questionable.",
  "\"Just one more semicolon,\" I said at 2am.",
  "I don't always write tests, but when I do, I forget to run them.",
  "Debugging is like being a detective in a crime movie where you're also the murderer.",
  "My variable names are 80% of my codebase's personality.",
  "npm install: the modern way to gamble your Saturday away.",
  "I learned to code so I could automate... nothing. I still do everything manually.",
  "\"It's a feature, not a bug\" — every student dev, ever.",
  "I spent more time choosing a terminal theme than learning git rebase.",
  "My code compiles. I am become death, destroyer of bugs.",
  "IDE said \"this will never work\" and honestly? Fair.",
  "I have 12 browser tabs open. None of them are the documentation.",
  "Ctrl+C, Ctrl+V is my debugging workflow.",
  "My TODO list is just a museum of abandoned ideas.",
  "I don't make mistakes. I create learning opportunities.",
  "\"It works on Linux\" — well, good for Linux.",
  "I wrote a function. I wrote another function. Now I have two problems.",
  "The rubber duck on my desk knows more about my code than I do.",
  "I'm not lazy; I just prefer to code inefficiently and call it \"brute force.\"",
  "I resonate with the initial readme of git.",
  "I refactored the code. It now breaks in cleaner ways.",
  "I don't fear production. Production fears me.",
  "My commit messages are just emotional journaling.",
  "The bug isn't random. It's just creatively scheduled.",
  "I installed one dependency. It installed 4,732 friends.",
  "I understand recursion. I understand recursion. I understand recursion.",
  "I fixed the bug. Three new ones have applied for residency.",
  "I said I'd document it later. Later has filed a restraining order.",
  "My code doesn't crash. It aggressively negotiates with reality."
]