export const jokes = [
  "My code has two modes: \"it works\" or \"I have no idea what's happening.\"",
  "VS Code: 47 extensions. Productivity: questionable.",
  "\"Just one more semicolon,\" I said at 2am.",
  "I don't always write tests, but when I do, I forget to run them.",
  "Debugging is like being a detective in a crime movie where you're also the murderer.",
  "My variable names are 80% of my codebase's personality.",
  "npm install: the modern way to gamble your Saturday away.",
  "I learned to code so I could automate... nothing. I still do everything manually.",
  "\"It's a feature, not a bug\" — every student dev, ever.",
  "I spent more time choosing a terminal theme than learning git rebase.",
  "My code compiles. I am become death, destroyer of bugs.",
  "IDE said \"this will never work\" and honestly? Fair.",
  "I have 12 browser tabs open. None of them are the documentation.",
  "Ctrl+C, Ctrl+V is my debugging workflow.",
  "My TODO list is just a museum of abandoned ideas.",
  "I don't make mistakes. I create learning opportunities.",
  "\"It works on Linux\" — well, good for Linux.",
  "I wrote a function. I wrote another function. Now I have two problems.",
  "The rubber duck on my desk knows more about my code than I do.",
  "I'm not lazy; I just prefer to code inefficiently and call it \"brute force.\"",
  "I resonate with the initial readme of git.",
  "I refactored the code. It now breaks in cleaner ways.",
  "I don't fear production. Production fears me.",
  "My commit messages are just emotional journaling.",
  "The bug isn't random. It's just creatively scheduled.",
  "I installed one dependency. It installed 4,732 friends.",
  "I understand recursion. I understand recursion. I understand recursion.",
  "I fixed the bug. Three new ones have applied for residency.",
  "I said I'd document it later. Later has filed a restraining order.",
  "My code doesn't crash. It aggressively negotiates with reality.",
  "I put my code in production. Once. Never again.",
  "Stack Overflow: where I go to confirm I'm not crazy (or realize I am).",
  "My code is on GitHub. My confidence is not.",
  "I read the error message. I understood nothing. Progress!",
  "\"Works on my machine\" should be a valid deployment strategy.",
  "I named a variable 'data' and another 'data2'. I'm a genius.",
  "Regular expressions: now you have two problems.",
  "My GitHub contribution graph is just a sin wave of procrastination.",
  "I tried to learn Vim. I still don't know how to exit.",
  "Comments in my code: optimistic lies about future readability.",
  "\"Can you just quick look at this?\" — every bug ever.",
  "I don't break code. I unoptimize it for performance.",
  "The console.log is mightier than the debugger.",
  "I spent 3 hours debugging only to find a missing comma.",
  "My code style: inconsistent, but inconsistently inconsistent.",
  "Classes? In my JavaScript? It's more likely than you think.",
  "I made a function. Now the entire app is one function. Efficiency!",
  "Git merge conflicts: the ultimate test of patience.",
  "I finally fixed it. I will never know what actually broke it.",
  "Backups? What backups?",
  "My GitHub profile is just a graveyard of 'initial commit'.",
  "Console warnings? That's just the browser being dramatic.",
  "I wrote clean code once. The IDE got confused and flagged it as suspicious.",
  "Auto-save: the reason I never learn to save manually.",
  "I showed my code to a senior dev. They just nodded slowly.",
  "The bug was between the keyboard and chair all along.",
  "I don't use debugging tools. I use strategic console.log placement.",
  "Code review feedback: 'creative interpretation of the requirements.'",
  "I learned to code in school. Then I learned how to actually code. They're different.",
  "Semicolons are optional. My confidence is not.",
  "I put everything in global scope. We're global people here.",
  "CSS: when 'how' is harder than 'what'.",
  "I made a website. It works on my screen. That's what matters.",
  "The documentation said 'simple setup.' The documentation lied.",
  "I asked AI for help. It gave me code that looks right but definitely isn't.",
  "Unit tests? I prefer integration testing in production.",
  "I renamed the file. Now nothing works. Classic.",
  "Array index starts at 0. My motivation starts at negative infinity.",
  "I finally understand closures. I'll forget by Tuesday.",
  "One more coffee. One more bug. Same thing.",
  "The error message said 'undefined is not a function.' Fair enough.",
  "I made a To-Do app. Now I have 47 To-Dos and 0 motivation."
];
